Feature/uot 103593
dod-advana/gamechanger-ml pull request #28
Opened 2021-07-14 19:29 UTC by jgrundy

things in this PR:

- updated post-processing util functions for predict_table.py
- functionality for hidden RE output filter
- adjusted how predict_table summary stats are output
- new script for creating per-document entity link % report

2021-07-16 15:39 UTC, cskiz commented on gamechangerml/src/text_classif/utils/classifier_post_utils.py
> +            primary_orgs.append(temp)
`temp` may be referenced before it is assigned. Suggest moving `temp = []` prior to `if "(" in j`.

2021-07-16 15:41 UTC, cskiz commented on gamechangerml/src/text_classif/utils/classifier_post_utils.py
> +def _agg_stats(df, model_name='NA', seq_len='NA', batch_size='NA'):
The defaults here should be _reasonable_, i.e., `batch_size` and `seq_len` are `int` types. Since these are not checked, I would remove the defaults altogether.

2021-07-16 15:45 UTC, cskiz commented on gamechangerml/src/text_classif/utils/predict_table.py
> +        action="store_false",
"store_true" and "store_false" are intended to be boolean flags. You can safely delete `action=...`. You'll need to alter how you retrieve the argument. In this case it's reference is `args.stats_path`.

2021-07-16 15:48 UTC, cskiz commented on gamechangerml/src/text_classif/utils/predict_table.py
> +        model = model_path.split('/')[-1]
Suggest changing this to `model = os.path.split(model_path)[-1]`. `os.path.split()` is purpose-built.

2021-07-16 15:50 UTC, cskiz requested changes
Comments in-line. Obviously you'll resolve merge conflicts. The `dev` branch got ahead of you :)

2021-07-19 16:13 UTC, cWren0110 commented
I don't think I have any other notes.  Let me know once Chris' comments are addressed and we can merge.

2021-07-21 19:25 UTC, jgrundy commented on gamechangerml/src/text_classif/utils/classifier_post_utils.py
> +            primary_orgs.append(temp)
Changed

2021-07-21 19:26 UTC, jgrundy commented on gamechangerml/src/text_classif/utils/classifier_post_utils.py
> +def _agg_stats(df, model_name='NA', seq_len='NA', batch_size='NA'):
Removed.

2021-07-21 19:27 UTC, jgrundy commented on gamechangerml/src/text_classif/utils/predict_table.py
> +        model = model_path.split('/')[-1]
Changed.

2021-07-21 19:27 UTC, jgrundy commented on gamechangerml/src/text_classif/utils/predict_table.py
> +        action="store_false",
Learned a thing today about the difference between 'action' and 'default' in parser.add_argument(). Changed.

2021-07-21 21:10 UTC, jgrundy reviewed
Comments reviewed and edits made. Merge errors have been resolved.

2021-07-21 21:28 UTC, jgrundy reviewed
Comments addressed.

2021-07-22 18:30 UTC, cskiz approved these changes
Ta da!

2021-07-22 18:31 UTC, merged