Feature/uot 105734 - Evaluation Pipeline
dod-advana/gamechanger-ml pull request #33
Opened 2021-07-26 18:55 UTC by katerdowdy

For testing the retriever, similarity model, and QA model with their original fine-tuning data and in-domain GC data. 

New files:
- README.md - added stuff about how to use the classes/run all of them to test
- `scripts/run_evaluation.py` - for testing all the model pipelines at once
- `src/model_testing/evaluation.py` - has the pipeline classes (different subclass for each validation dataset). So for testing just the encoder model after we make a new sentence index, we would use the `IndomainRetrieverEvaluator` to check if the gold standard docs are still showing up in the new index.
- `src/model_testing/validation.py` - has classes for each of the validation datasets to get them in a format to use for testing. For QA and the Retriever in domain datasets, we're also checking that the answers are in the context/docs in the index before we include those in the evaluation.
- `src/utilities/model_helper.py` - we could move these, functions for opening and saving files mostly
- `data/validation/QA_domain_data.json` - we might want to change this a little to make our QA data more versatile (we can use it for evaluating the retriever and sim model) but showing the format of the examples we have now. 

Old files:
- `configs/config.py` - added more configs for the other transformers and validation datasets
- `src/search/sent_transformer/model.py` - I had to change some of this to be able to test the retriever and sim model separately, but I was able to use it to make an index locally so I think it should still work.
- `src/search/QA/QAReader.py` - preserving caps in questions for better answers

2021-07-30 15:23 UTC, cWren0110 commented on gamechangerml/configs/config.py
> +#from gamechangerml.api.utils.pathselect import get_model_paths
Should these commented lines be removed?

2021-07-30 15:23 UTC, cWren0110 commented on gamechangerml/scripts/run_evaluation.py
> +from gamechangerml.src.model_testing.evaluation import SQuADQAEvaluator, IndomainQAEvaluator, IndomainRetrieverEvaluator, MSMarcoRetrieverEvaluator, SimilarityEvaluator
Are the metrics generated in this script captured anywhere? Confluence, MLFlow, etc.?

2021-07-30 15:26 UTC, rha930 commented on gamechangerml/scripts/run_evaluation.py
> +from gamechangerml.src.model_testing.evaluation import SQuADQAEvaluator, IndomainQAEvaluator, IndomainRetrieverEvaluator, MSMarcoRetrieverEvaluator, SimilarityEvaluator
they will be soon, i think originally they were on confluence from prince for baseline stuff

2021-07-30 15:34 UTC, katerdowdy commented on gamechangerml/scripts/run_evaluation.py
> +from gamechangerml.src.model_testing.evaluation import SQuADQAEvaluator, IndomainQAEvaluator, IndomainRetrieverEvaluator, MSMarcoRetrieverEvaluator, SimilarityEvaluator
The metrics are explained somewhat in the README in model_testing, but I also updated Confluence here: https://confluence.di2e.net/x/jDpPT. If anybody has thoughts on other metrics we want, we can add those

2021-07-30 15:35 UTC, cWren0110 approved these changes

2021-07-30 15:48 UTC, rha930 commented
is the old stuff OBE in model_test/

2021-07-30 15:57 UTC, katerdowdy commented
> is the old stuff OBE in model_test/

I just removed the old files

2021-08-02 15:08 UTC, rha930 requested changes
QA in the API params need to be fixed

2021-08-02 19:10 UTC, katerdowdy commented
> QA in the API params need to be fixed

This should be working now, here's what I get from health check in API: ```gc-ml-gpu             | 2021-08-02 19:05:41,982 [INFO][PID:18]: -- Sentence index name: gamechangerml/models/sent_index
gc-ml-gpu             | 2021-08-02 19:05:41,983 [INFO][PID:18]: -- QE model name: gamechangerml/models/qexp_20201217
gc-ml-gpu             | 2021-08-02 19:05:41,984 [INFO][PID:18]: -- QA model name: gamechangerml/models/transformers/bert-base-cased-squad2
gc-ml-gpu             | 2021-08-02 19:07:41,899 [INFO][PID:18]: API Health Check
gc-ml-gpu             | 2021-08-02 19:07:41,902 [INFO][PID:18]: Model Health: GOOD
gc-ml-gpu             | 2021-08-02 19:07:41,903 [INFO][PID:18]: -- Sentence Transformer model name: {'encoder': 'gamechangerml/models/transformers/msmarco-distilbert-base-v2', 'sim': 'gamechangerml/models/transformers/distilbart-mnli-12-3'}```

2021-08-05 17:53 UTC, rha930 approved these changes

2021-08-05 17:53 UTC, merged