Classifier glob entities
dod-advana/gamechanger-ml pull request #4
Opened 2021-05-14 19:25 UTC by jgrundy

PR for work from output-shaping work done on classifiers-glob-entities into core classifier work by Chris.

2021-05-17 13:06 UTC, cskiz requested changes
Comments / changes are inline

2021-05-17 13:06 UTC, cskiz commented on src/text_classif/utils/predict_table.py
> +        entity_coref = EntityCoref()
This can be outside the loop.

2021-05-17 16:49 UTC, jgrundy commented on src/featurization/abbreviations_utils.py
> +from common.document_parser.issuance_ref import collect_ref_list
Updated reference.

2021-05-17 17:58 UTC, cWren0110 commented
Please do not include __pycache__ files/folders.

2021-05-17 18:03 UTC, cskiz commented
> Please do not include **pycache** files/folders.

The `.gitignore` should take care of this. In `dataScience/` there is a `Makefile` that will clean up these sorts of files / directories.

2021-05-17 20:18 UTC, cWren0110 requested changes

2021-05-18 18:37 UTC, rha930 commented on src/featurization/abbreviations_utils.py
> +import pandas as pd
it looks like dev was merged in, but this isnt going to dev

2021-05-18 19:41 UTC, cskiz commented on src/featurization/extract_improvement/extract_utils.py
> +import pandas as pd
`extract_utils.py` & `extract_responsibilities` are part of the repo migration (they're not new).

2021-05-19 18:16 UTC, jgrundy commented on src/featurization/abbreviations_utils.py
> +import pandas as pd
re-added from repo migration.

2021-05-19 18:16 UTC, jgrundy commented on src/featurization/extract_improvement/extract_responsibilities.py
> +import pandas as pd
re-added from repo migration

2021-05-19 18:17 UTC, jgrundy commented on src/featurization/extract_improvement/extract_utils.py
> +import pandas as pd
chris is correct. these are being brought over as part of the repo migration since they contain utils we use for predict_table.py. they were originally on one of erin's feature branches.

2021-05-19 18:25 UTC, jgrundy commented on src/text_classif/utils/predict_table.py
> +        entity_coref = EntityCoref()
changed.

2021-05-19 18:25 UTC, jgrundy commented on src/featurization/abbreviations_utils.py
> +    # agencies = list(df["Agency_Name"])
changed.

2021-05-19 20:01 UTC, jgrundy commented on api/docker-compose.yml
>          reservations:
agreed. artifact of moving things over.

2021-05-19 20:24 UTC, jgrundy commented on src/search/sent_transformer/create_embedding.py
> -from dataScience.src.search.sent_transformer.model import SentenceEncoder
looks like it was deleted in another commit anyway.

2021-05-19 20:26 UTC, merged