Task/uot 122338 - cleaning up features in pipeline
dod-advana/gamechanger-ml pull request #67
Opened 2021-11-29 20:16 UTC by katerdowdy

Details coming - adding in steps to make validation/training data at the same time

2021-12-09 18:41 UTC, vctrstrm commented on gamechangerml/scripts/get_wiki_descriptions.py
> +        entities_filepath = 'gamechangerml/data/features/combined_entities.csv'
it's a good idea to use abs paths for scenarios where current dir is other than repo dir and when gamechangerml is installed as a package, e.g. `os.path.join(gamechangerml.DATA_PATH, "features", "combined_entities.csv")` - same idea as elsewhere in the repo

2021-12-09 18:47 UTC, vctrstrm requested changes

2021-12-09 18:47 UTC, vctrstrm commented on gamechangerml/scripts/run_evaluation.py
> +            data_path = os.path.join('gamechangerml/data/validation/domain/sent_transformer', validation_data)
similar to previous comment, this would be more robust with abs path joined off gamechangerml.DATA_PATH

2021-12-09 18:47 UTC, vctrstrm commented on gamechangerml/scripts/update_eval_data.py
> +SUB_DIR = "gamechangerml/data/validation/domain/sent_transformer"
ditto - better to use abs path based on gamechangerml.DATA_PATH

2021-12-09 18:47 UTC, vctrstrm commented on gamechangerml/src/featurization/generated_fts.py
> +popular_df = pd.read_csv("gamechangerml/data/features/popular_documents.csv")
ditto - better to use abs path based on gamechangerml.DATA_PATH

2021-12-09 18:47 UTC, vctrstrm commented on setup.py
> +REQUIREMENTS_PATH = Path(ROOT_PATH, "lock.requirements.txt")
these changes should not be needed anymore, the current setup.py on <dev> branch fixes the syntax error that broke it previously

2021-12-09 18:47 UTC, vctrstrm commented on lock.requirements.txt
> +#faiss-gpu==1.7.1.post2
shouldn't need to comment this out, since setup.py already filters out faiss-gpu when installed on non-linux systems

2021-12-09 18:47 UTC, vctrstrm commented on requirements.txt
> +#faiss-gpu~=1.7.1
ditto

2021-12-09 19:43 UTC, katerdowdy commented on gamechangerml/scripts/run_evaluation.py
> +            data_path = os.path.join('gamechangerml/data/validation/domain/sent_transformer', validation_data)
changed to import & use DATA_PATH

2021-12-09 19:43 UTC, katerdowdy commented on gamechangerml/scripts/update_eval_data.py
> +SUB_DIR = "gamechangerml/data/validation/domain/sent_transformer"
changed to import & use DATA_PATH

2021-12-09 19:44 UTC, katerdowdy commented on setup.py
> +REQUIREMENTS_PATH = Path(ROOT_PATH, "lock.requirements.txt")
removed the "lock" (is that what you meant?)

2021-12-09 19:44 UTC, katerdowdy commented on lock.requirements.txt
> +#faiss-gpu==1.7.1.post2
uncommented faiss gpu

2021-12-09 19:44 UTC, katerdowdy commented on requirements.txt
> +#faiss-gpu~=1.7.1
uncommented faiss gpu

2021-12-09 19:55 UTC, katerdowdy commented on gamechangerml/scripts/get_wiki_descriptions.py
> +        entities_filepath = 'gamechangerml/data/features/combined_entities.csv'
changed to import & use DATA_PATH

2021-12-09 22:49 UTC, vctrstrm requested changes

2021-12-09 22:49 UTC, vctrstrm commented on gamechangerml/api/fastapi/routers/controls.py
> +            #try:
can we cut out commented section if not needed?

2021-12-09 22:49 UTC, vctrstrm commented on gamechangerml/api/fastapi/routers/controls.py
> +            #    "retriever": retriever
can we cut out commented section if not needed?

2021-12-09 22:49 UTC, vctrstrm commented on gamechangerml/api/fastapi/model_loader.py
> +#SENT_INDEX_PATH.value = 'gamechangerml/models/sent_index_TEST'
can we cut out commented section if not needed?

2021-12-10 16:50 UTC, vctrstrm approved these changes

2021-12-20 19:57 UTC, rha930 approved these changes

2021-12-20 19:57 UTC, merged